### ISSUE TITLE
Bug report: Observed limits affecting expected limits

### ISSUE THREAD

**Issue by bregnery** [boostedsvj/svj_limits#14]
This is quite an edge case and took a look of digging into the code to understand what is happening. All of this is happening within `quick_plot.py`

In`interpolate_95cl_limit` there is the following line: 
```
select = ((cl < .99) & (cl > .001) & (mu>0))
```

Which fails due to a 'nan' in 's' caused by a zero in 'b'

This all comes from the calculation of 'b' which relies on q_asimov and q_observed

```
b = np.where(
    q_obs <= q_A,
    norm.cdf(np.sqrt(q_A) - np.sqrt(q_obs)),  
    1. - norm.cdf(safe_divide(.5 * (q_obs - q_A), np.sqrt(q_A)))  
)
```

More specifically, we have a case with `q_obs = 3.16080165` and `q_A = 0.0167024769`

This leads to the following calculation
```
safe_divide = 1.57204958655 / 0.1292323748
            ≈ 12.16056373
# then 
norm.cdf(12.16056373) 
# which is very large and essentially 1.0
# so
b = 1.0 - 1.0 = 0
```

**Comment by kpedro88** [comment]
Try using `norm.sf()` instead of `1-norm.cdf()`. (sf = "survival function" in scipy, https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.norm.html#scipy.stats.norm)

If that helps, we should switch to that for all `1-norm.cdf()` statements

**Comment by bregnery** [comment]
So that leads to the value `2.41714574e-34` which becomes `0.0` in the s calculation. So that gets rid of the nan problem.

However, this somehow this still has issues during interpolation.

**Comment by kpedro88** [comment]
Have you compared the actual likelihoods for the weird case vs. a normal case, to check if the fit converged well?

**Comment by bregnery** [comment]
These are the likelihoods for the 'observed' which has a signal injected at 450 (first plot) and the asimov (second plot). They seem good to me.

![obs_muscan](https://github.com/user-attachments/assets/5874491e-c641-41a1-bc79-4c9c07fd0eae)
![asimov_muscan](https://github.com/user-attachments/assets/8a3848b6-45b6-44b5-96a5-c3a8cea32235)

**Comment by bregnery** [comment]
Okay, this is bizzare, I made sure that the asimov file is exactly the same between these two tests. Here, I am just printing `q_A`

```
INFO:2024-12-05 11:26:16:boosted_fits:136 Running brazil
q_A  [2.50342102e+02 2.13223236e+02 5.76684380e+01 4.08399582e+01
 1.92444210e+01 1.33668928e+01 8.33179092e+00 4.21559238e+00
 1.28523004e+00 1.67024769e-02 8.05983245e-01 1.31184711e+01
 7.89698868e+01 1.06548340e+02 1.20994682e+02 1.35916885e+02
 2.00032257e+02 2.15930847e+02 3.77994049e+02 3.94159760e+02
 4.42255920e+02 4.58134705e+02 4.78830750e+02 4.94138153e+02
 5.09350311e+02 5.24466003e+02 5.39484253e+02 5.54404541e+02
 5.69226257e+02 5.83949585e+02 5.98573975e+02 6.13099915e+02
 6.27528137e+02 6.41857422e+02 6.56089844e+02 6.70225220e+02
 6.84264526e+02 6.98208008e+02 7.12056763e+02 7.25811340e+02
 7.39472839e+02 7.53041870e+02 7.66519592e+02 7.88129333e+02
 7.93203491e+02 8.06412048e+02 8.26521912e+02 8.39113098e+02
 8.45514954e+02 8.58378113e+02]
mz     2s down  1s down      exp    1s up    2s up |      obs
300     +0.313   +0.296   +0.071   +0.071   +0.071 |   +0.071

INFO:2024-12-05 11:27:26:boosted_fits:136 Running brazil
q_A  [2.50342102e+02 2.01181808e+02 5.76684380e+01 1.92444210e+01
 1.33668928e+01 8.33179092e+00 4.21559238e+00 1.28523004e+00
 1.67024769e-02 8.05983245e-01 3.47973418e+00 1.31184711e+01
 1.97303600e+01 4.56833229e+01 1.20994682e+02 1.35916885e+02
 1.51225891e+02 1.68678177e+02 4.26305115e+02 4.42255920e+02
 4.78830750e+02 5.83949585e+02 5.98573975e+02 6.13099915e+02
 6.27528137e+02 6.41857422e+02 6.56089844e+02 6.70225220e+02
 6.84264526e+02 6.98208008e+02 7.12056763e+02 7.25811340e+02
 7.39472839e+02 7.53041870e+02 7.66519592e+02 7.88129333e+02
 7.93203491e+02 8.06412048e+02 8.26521912e+02 8.39113098e+02
 8.45514954e+02 8.58378113e+02]
mz     2s down  1s down      exp    1s up    2s up |      obs
300     +0.313   +0.281   +0.152   +0.134   +0.105 |   +0.118
```

Somehow `q_A` is being changed... investigating more

**Comment by bregnery** [comment]
I found something in `get_cls`

```
    # Keep only scan points where both obs and asimov have a mu
    keep_obs = np.isin(obs.df['mu'], asimov.df['mu'])
    keep_asimov = np.isin(asimov.df['mu'], obs.df['mu'])
    obs = obs[keep_obs]
    asimov = asimov[keep_asimov]
```
So it is masking the values when they don't have a corresponding value in the obs dataset. 

Before `keep_asimov` is applied:
```
Asimov mu:  [-2.19191909 -2.11111116 -1.94949496 -1.86868691 -1.5454545  -1.38383842
 -1.30303025 -1.22222221 -0.81818181 -0.65656567 -0.41414142 -0.33333334
 -0.25252524 -0.17171717 -0.09090909 -0.01010101  0.07070707  0.15151516
  0.3131313   0.39393941  0.47474748  0.63636363  0.87878788  0.95959598
  1.04040408  1.12121212  1.20202017  1.28282833  1.44444442  1.52525258
  1.60606062  2.090909    2.17171717  2.33333325  2.41414142  2.5757575
  2.65656567  2.73737383  2.81818175  2.89898992  2.97979808  3.060606
  3.14141417  3.22222233  3.30303025  3.38383842  3.46464658  3.5454545
  3.62626266  3.70707059  3.78787875  3.86868691  3.94949484  4.030303
  4.11111116  4.19191933  4.27272749  4.35353518  4.43434334  4.5151515
  4.59595966  4.67676783  4.75757599  4.83838367  4.91919184  5.        ]
```
When it is applied for the 'good' observed file with mZ 400 injected signal:
```
Asimov mu:  [-2.11111116 -1.86868691 -0.81818181 -0.41414142 -0.33333334 -0.25252524
 -0.17171717 -0.09090909 -0.01010101  0.07070707  0.15151516  0.3131313
  0.39393941  0.63636363  1.04040408  1.12121212  1.20202017  1.28282833
  2.5757575   2.65656567  2.81818175  3.38383842  3.46464658  3.5454545
  3.62626266  3.70707059  3.78787875  3.86868691  3.94949484  4.030303
  4.11111116  4.19191933  4.27272749  4.35353518  4.43434334  4.5151515
  4.59595966  4.67676783  4.75757599  4.83838367  4.91919184  5.        ]
```

Then for the 'bad' observed file with mZ 450 injected signal:
```
Asimov mu:  [-2.11111116 -1.94949496 -0.81818181 -0.65656567 -0.41414142 -0.33333334
 -0.25252524 -0.17171717 -0.09090909 -0.01010101  0.07070707  0.3131313
  0.87878788  0.95959598  1.04040408  1.12121212  1.44444442  1.52525258
  2.33333325  2.41414142  2.65656567  2.73737383  2.81818175  2.89898992
  2.97979808  3.060606    3.14141417  3.22222233  3.30303025  3.38383842
  3.46464658  3.5454545   3.62626266  3.70707059  3.78787875  3.86868691
  3.94949484  4.030303    4.11111116  4.19191933  4.27272749  4.35353518
  4.43434334  4.5151515   4.59595966  4.67676783  4.75757599  4.83838367
  4.91919184  5.        ]
```

These varying asimov mu values mean that the `q_A` values will be different, which means that the `s_exp` will be different.

I literally have no idea what to do about this, I don't really understand why this is in the code.

**Comment by kpedro88** [comment]
This is done because the numerical operations on `q_obs` and `q_A` assume they are the same length and represent the same signal strength points. Interpolation only happens at the end, for the CLs curves.

I'm still surprised that this could cause such a big change in the expected limit. What do the CLs plots look like?

**Comment by bregnery** [comment]
The CLs plot looks very weird to me

![test](https://github.com/user-attachments/assets/d8b29c37-f07e-422b-b590-97ded514365f)

**Comment by bregnery** [comment]
Here is the CLs plot for signal injected at 400 (which has the same expected limits as all other values)

![cls_400_siginj](https://github.com/user-attachments/assets/c88a2e69-5aa3-4884-9bc6-3f23dacb8f93)

**Comment by bregnery** [comment]
Found that this line is currently affecting the likelihood scan and must be adjusted manually

https://github.com/boostedsvj/svj_limits/blob/main/boosted_fits.py#L1787

**Comment by kpedro88** [comment]
@bregnery that was issue #4 which was fixed by https://github.com/boostedsvj/svj_limits/commit/cce433a61370049c7aacce403da67187c5708b99. Are you using the latest version?

**Comment by bregnery** [comment]
@kpedro88 that's what I thought too, but I am wondering if something got messed up when we removed a few commits.

The line I linked is directly on the latest version of the main branch

**Comment by bregnery** [comment]
So this issue here is not so much with the observed limit affecting the expected limits, rather, the role that `--rMax` and `--rMin` can't be used in our repo and instead, we need to use `--range`

`--rMax` and `--rMin` will print as if they were passed to combine correctly... this is still a bug and I am not sure how to fix it, but I think it is worth closing this bug report
